### ISSUE TITLE
Proxy error while non root

### ISSUE THREAD

**Issue by jere19** [jupyter/jupyterhub#164]
I've just installed jupyterhub and tested it successfully running it as root.
However, following the non-root procedure end up on a proxy error after being logged in:
```
rhea@pcjlaforet-cr:/etc/jupyterhub$  jupyterhub --JupyterHub.spawner_class=sudospawner.SudoSpawner
[I 2015-03-03 17:41:32.475 JupyterHub app:506] Loading cookie_secret from /etc/jupyterhub/jupyterhub_cookie_secret
[W 2015-03-03 17:41:32.504 JupyterHub app:242] 
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    
[I 2015-03-03 17:41:32.511 JupyterHub app:599] Not using whitelist. Any authenticated user will be allowed.
[I 2015-03-03 17:41:32.523 JupyterHub app:731] Starting proxy @ http://*:8000/
17:41:32.633 - info: [ConfigProxy] Proxying http://*:8000 to http://localhost:8081
17:41:32.635 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes
[I 2015-03-03 17:41:42.694 JupyterHub web:1825] 302 GET / (127.0.0.1) 1.45ms
[I 2015-03-03 17:41:42.700 JupyterHub web:1825] 302 GET /hub (127.0.0.1) 0.34ms
[I 2015-03-03 17:41:42.710 JupyterHub web:1825] 302 GET /hub/ (127.0.0.1) 5.91ms
[I 2015-03-03 17:41:42.747 JupyterHub web:1825] 200 GET /hub/home (127.0.0.1) 33.46ms
[I 2015-03-03 17:41:42.906 JupyterHub web:1825] 200 GET /hub/static/js/home.js?v=(%2720150303174132%27,) (127.0.0.1) 5.62ms
[I 2015-03-03 17:41:42.917 JupyterHub web:1825] 200 GET /hub/static/components/jquery/jquery.min.js?v=(%2720150303174132%27,) (127.0.0.1) 2.20ms
[I 2015-03-03 17:41:42.919 JupyterHub web:1825] 200 GET /hub/static/js/jhapi.js?v=(%2720150303174132%27,) (127.0.0.1) 0.70ms
[I 2015-03-03 17:41:42.961 JupyterHub web:1825] 200 GET /hub/static/js/utils.js?v=(%2720150303174132%27,) (127.0.0.1) 0.88ms
[I 150303 17:41:45 mediator:62] Spawning /usr/bin/python3 -m jupyterhub.singleuser --user=jlaforet --port=46992 --cookie-name=jupyter-hub-token-jlaforet --base-url=/user/jlaforet --hub-prefix=/hub/ --hub-api-url=http://localhost:8081/hub/api --ip=localhost
[I 2015-03-03 17:41:45.929 JupyterHub base:209] User jlaforet server took 0.893 seconds to start
[I 2015-03-03 17:41:45.929 JupyterHub orm:154] Adding user jlaforet to proxy /user/jlaforet => http://*:46992
[I 2015-03-03 17:41:45.939 JupyterHub web:1825] 302 GET /hub/user/jlaforet/ (127.0.0.1) 908.02ms
17:41:46.086 - error: [ConfigProxy] Proxy error:  code=ENOTFOUND, errno=ENOTFOUND, syscall=getaddrinfo
```

Feels like there's something misconfigured for the proxy, but i have no clue what.

**Comment by minrk** [comment]
Can you run it again with:

    --debug --JupyterHub.debug_db=True

?

**Comment by mfitzp** [comment]
I'm experiencing the same issue after following the instructions for [Using sudo to run JupyterHub without root privileges](https://github.com/jupyter/jupyterhub/wiki/Using-sudo-to-run-JupyterHub-without-root-privileges). It works fine as a single-user running as root via sudo. 

After starting the server and navigating the front page it displays correctly. The login works, making it to the "My Server" green button.  Clicking this however produces the proxy error: the resulting page has the message `Proxy target missing`

    http://<ip-address>:8000/hub/home      [...click green button...]
    http://<ip-address>:8000/user/mfitzp/    Proxy target missing

Alongside the displayed message is the similar output to @jere19 described above.

    [I 2015-03-04 17:38:51.370 JupyterHub web:1825] 302 GET /hub/user/mfitzp/ (<ip-address>) 565.94ms
    17:38:51.380 - error: [ConfigProxy] Proxy error:  code=ENOTFOUND, errno=ENOTFOUND, syscall=getaddrinfo

Running the server with `--debug --JupyterHub.debug_db=True` produces the following output. I've trimmed it for the highlighted lines and information regarding proxy/users (removing the SQL debug from SQLAlchemy - happy to provide if it will be helpful).

    Connecting to db: sqlite:///jupyterhub.sqlite
    [W 2015-03-04 17:41:26.368 JupyterHub app:242]
    Generating CONFIGPROXY_AUTH_TOKEN. Restarting the Hub will require restarting the proxy.
    Set CONFIGPROXY_AUTH_TOKEN env or JupyterHub.proxy_auth_token config to avoid this message.
    [I 2015-03-04 17:41:26.376 JupyterHub app:599] Not using whitelist. Any authenticated user will be allowed.

    [D 2015-03-04 17:41:26.379 JupyterHub app:671] Loaded users:
     jupyter admin
      mfitzp

    [I 2015-03-04 17:41:26.392 JupyterHub app:731] Starting proxy @ http://*:8000/
    [D 2015-03-04 17:41:26.392 JupyterHub app:732] Proxy cmd: ['configurable-http-proxy', '--ip', '', '--port', '8000', '--api-ip', 'localhost', '--api-port', '8001', '--default-target', 'http://localhost:8081']

    17:41:26.500 - info: [ConfigProxy] Proxying http://*:8000 to http://localhost:8081
    17:41:26.503 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes

    [D 2015-03-04 17:41:26.609 JupyterHub app:752] Proxy started and appears to be up

    [D 2015-03-04 17:43:28.456 JupyterHub utils:73] Server at http://localhost:53906/user/mfitzp responded with 302
    [I 2015-03-04 17:43:28.457 JupyterHub base:209] User mfitzp server took 1.689 seconds to start
    [I 2015-03-04 17:43:28.457 JupyterHub orm:154] Adding user mfitzp to proxy /user/mfitzp => http://*:53906

    [D 2015-03-04 17:43:28.460 JupyterHub orm:141] Fetching POST http://localhost:8001/api/routes/user/mfitzp

    [I 2015-03-04 17:43:28.472 JupyterHub web:1825] 302 GET /hub/user/mfitzp/ (<ip-address>) 1715.60ms
    17:43:28.767 - error: [ConfigProxy] Proxy error:  code=ENOTFOUND, errno=ENOTFOUND, syscall=getaddrinfo

I'm running with today's master from Github.

**Comment by minrk** [comment]
Thanks, I'll see if I can pin down what's wrong.

**Comment by minrk** [comment]
The problem was caused by #160, and is doubly fixed by #165 and jupyter/sudospawner@671540c3060c736f2064fcc2bc239a200b0be186

**Comment by jfemiani** [comment]
I am still getting this exact same issue.
I am using master, which I downloaded today. 
I am on Ubuntu14.03.2 
```#!bash

myname@mycomputer:~$ sudo jupyterhub
/usr/local/lib/python3.4/dist-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
[I 2015-12-02 19:14:41.476 JupyterHub app:522] Loading cookie_secret from /home/likewise-open/ASUAD/myname/jupyterhub_cookie_secret
[I 2015-12-02 19:14:41.501 JupyterHub app:656] Not using whitelist. Any authenticated user will be allowed.
[I 2015-12-02 19:14:41.509 JupyterHub app:1037] Hub API listening on http://localhost:8081/hub/
[I 2015-12-02 19:14:41.512 JupyterHub app:793] Starting proxy @ http://*:8000/
19:14:41.648 - info: [ConfigProxy] Proxying http://*:8000 to http://localhost:8081
19:14:41.650 - info: [ConfigProxy] Proxy API at http://localhost:8001/api/routes
[I 2015-12-02 19:14:41.718 JupyterHub app:1060] JupyterHub is now running at http://localhost:8000/
[I 2015-12-02 19:14:46.050 JupyterHub log:100] 302 GET /user/myname/ (@127.0.0.1) 2.29ms
Last login: Wed Dec  2 19:13:24 MST 2015
Welcome to Ubuntu 14.04.2 LTS (GNU/Linux 3.16.0-30-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

[I 2015-12-02 19:14:46.269 JupyterHub spawner:363] Spawning jupyterhub-singleuser --user=myname --port=56833 --cookie-name=jupyter-hub-token-myname --base-url=/user/myname --hub-prefix=/hub/ --hub-api-url=http://localhost:8081/hub/api '--ip=*'
/usr/local/lib/python3.4/dist-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
[W 2015-12-02 19:14:48.940 myname notebookapp:254] ipywidgets package not installed.  Widgets are unavailable.
[W 2015-12-02 19:14:48.945 myname login:91] WARNING: The notebook server is listening on all IP addresses and not using encryption. This is not recommended.
[W 2015-12-02 19:14:48.945 myname login:94] WARNING: The notebook server is listening on all IP addresses and not using authentication. This is highly insecure and not recommended.
[I 2015-12-02 19:14:48.965 myname notebookapp:1063] Serving notebooks from local directory: /home/likewise-open/ASUAD/myname
[I 2015-12-02 19:14:48.966 myname notebookapp:1063] 0 active kernels 
[I 2015-12-02 19:14:48.966 myname notebookapp:1063] The IPython Notebook is running at: http://[all ip addresses on your system]:56833/user/myname/
[I 2015-12-02 19:14:48.966 myname notebookapp:1064] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 2015-12-02 19:14:48.983 myname log:47] 302 GET /user/myname (::1) 0.74ms
[I 2015-12-02 19:14:48.985 JupyterHub base:296] User myname server took 2.924 seconds to start
[I 2015-12-02 19:14:48.985 JupyterHub orm:169] Adding user myname to proxy /user/myname => http://*:56833
[I 2015-12-02 19:14:49.007 JupyterHub log:100] 302 GET /hub/user/myname/ (mkatic@127.0.0.1) 2948.62ms
19:14:49.043 - error: [ConfigProxy] Proxy error:  code=ENOTFOUND, errno=ENOTFOUND, syscall=getaddrinfo
19:14:49.044 - error: [ConfigProxy] 503 GET /user/myname/

```

**Comment by minrk** [comment]
What do you get from `sudo jupyterhub --version` and `which -a jupyterhub`? Because the traitlets warning suggests that you do not, in fact, have the latest version.
